### ISSUE TITLE
LyricsWIkia no longer available - where can I access lyrics from

### ISSUE THREAD

**Issue by KING-SID** [micbuffa/WasabiDataset#2]
Seems like lyrics wikia is no longer accessible. How might I be able to access all the lyrics?

**Comment by micbuffa** [comment]
Indeed,  lyrics wikia has been shut down. You can use the MusixMatch API, that is free for getting  parts of song lyrics, and will require a plan to get the full lyrics. The API is very easy to use.

https://developer.musixmatch.com/plans allows you to get 30% of the lyrics for free and for non-commercial purposes, and if you pay, in full. URIs are the same whether you pay or not, and I quickly wrote a little bit of code in jsbin to test: [https://jsbin.com/janafox/edit?html,js,console](https://jsbin.com/janafox/edit?html,js,console)

https://api.musixmatch.com/ws/1.1/matcher.lyrics.get?format=json&q_track=SONG_TITLE&q_artist=ARTIST&apikey=<api_key>";
